<a href="https://colab.research.google.com/github/amitsingh6261/my_all_python_Program/blob/main/pandas%20fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# deffination of pandas
# pandas is an open source pyhton library used for data manipulation, data analylis, and handling structured data
#in the form of rows and columns.

In [360]:
import pandas as pd

df = {
    "Name":("Aman","Riya","Kabir","Neha","Aman","Amit"),
    "Age":(21,22,20,23,21,21),
    "City":("Delhi","Mumbai","Delhi","Pune","Delhi","Indore"),
    "Marks":(85,92,76,88,85,95),
    "Salary":(45000,52000,39000,61000,45000,90000)
}

In [361]:
df=pd.DataFrame(df)
df

    Name  Age    City  Marks  Salary
0   Aman   21   Delhi     85   45000
1   Riya   22  Mumbai     92   52000
2  Kabir   20   Delhi     76   39000
3   Neha   23    Pune     88   61000
4   Aman   21   Delhi     85   45000
5   Amit   21  Indore     95   90000

In [362]:
#show starting value
df.head(2)

   Name  Age    City  Marks  Salary
0  Aman   21   Delhi     85   45000
1  Riya   22  Mumbai     92   52000

In [363]:
#show last values
df.tail(3)

   Name  Age    City  Marks  Salary
3  Neha   23    Pune     88   61000
4  Aman   21   Delhi     85   45000
5  Amit   21  Indore     95   90000

In [364]:
#show total row and columns
df.shape

(6, 5)

In [365]:
# shoe all columns
df.columns

Index(['Name', 'Age', 'City', 'Marks', 'Salary'], dtype='object')

In [366]:
# show index
df.index

RangeIndex(start=0, stop=6, step=1)

In [367]:
# show data type
df.dtypes

Name      object
Age        int64
City      object
Marks      int64
Salary     int64
dtype: object

In [368]:
#df.info() → DataFrame ki basic information deta hai.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Marks   6 non-null      int64
 4   Salary  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

In [369]:
#df.describe() → Sirf numbers ka summary deta hai.
df.describe()

             Age      Marks        Salary
count   6.000000   6.000000      6.000000
mean   21.333333  86.833333  55333.333333
std     1.032796   6.615638  18575.970141
min    20.000000  76.000000  39000.000000
25%    21.000000  85.000000  45000.000000
50%    21.000000  86.500000  48500.000000
75%    21.750000  91.000000  58750.000000
max    23.000000  95.000000  90000.000000

In [370]:
#df.describe(include="all") → Saare columns ka summary deta hai.
df.describe(include="all")

        Name        Age   City      Marks        Salary
count      6   6.000000      6   6.000000      6.000000
unique     5        NaN      4        NaN           NaN
top     Aman        NaN  Delhi        NaN           NaN
freq       2        NaN      3        NaN           NaN
mean     NaN  21.333333    NaN  86.833333  55333.333333
std      NaN   1.032796    NaN   6.615638  18575.970141
min      NaN  20.000000    NaN  76.000000  39000.000000
25%      NaN  21.000000    NaN  85.000000  45000.000000
50%      NaN  21.000000    NaN  86.500000  48500.000000
75%      NaN  21.750000    NaN  91.000000  58750.000000
max      NaN  23.000000    NaN  95.000000  90000.000000

In [371]:
# select from DataFrame
df[['Name','Marks']]

    Name  Marks
0   Aman     85
1   Riya     92
2  Kabir     76
3   Neha     88
4   Aman     85
5   Amit     95

In [372]:
# select from  Series
df['Name']

0     Aman
1     Riya
2    Kabir
3     Neha
4     Aman
5     Amit
Name: Name, dtype: object

In [373]:
df.Name

0     Aman
1     Riya
2    Kabir
3     Neha
4     Aman
5     Amit
Name: Name, dtype: object

In [374]:
df.iloc[2,0]

'Kabir'

#  loc vs iloc

# loc = index/label dekhta hai (kis index per value hai)
# iloc = position dekhta hai(kis possion per value hai)
#loc → Label/Index aur column ke naam par kaam karta hai.
#Example: df.loc[1, "Name"]
#iloc → Integer position (0, 1, 2...) par kaam karta hai.
#Example: df.iloc[1, 0]

In [375]:
df.iloc[2,0]

'Kabir'

In [376]:
df.loc[2,'Name']

'Kabir'

# Filtering

# data filtering is the prosecc of selecting only the required data from a dataser based on the given condtion

In [377]:
dt=pd.DataFrame({
     "Name":['Amit','Rohit','Nitin','Ram','Shyam','Naman'],
     "Age":[21,43,54,23,54,65],
     "City":['Indore','pune','delhi','agra','noida','devash'],
     "Marks":[99,78,98,96,85,93]
 })

In [378]:
dt

    Name  Age    City  Marks
0   Amit   21  Indore     99
1  Rohit   43    pune     78
2  Nitin   54   delhi     98
3    Ram   23    agra     96
4  Shyam   54   noida     85
5  Naman   65  devash     93

In [379]:
dt['Marks']>95

0     True
1    False
2     True
3     True
4    False
5    False
Name: Marks, dtype: bool

In [380]:
dt[dt['Marks']>95]

    Name  Age    City  Marks
0   Amit   21  Indore     99
2  Nitin   54   delhi     98
3    Ram   23    agra     96

3. Filtering ka Basic Formula

Isko yaad kar lo:

df[df["column"] condition]

AND → &

OR  → |

In [381]:
dt[dt['Age']>45]

    Name  Age    City  Marks
2  Nitin   54   delhi     98
4  Shyam   54   noida     85
5  Naman   65  devash     93

In [382]:
#99 ko chhod kar
dt[dt['Marks']!=99]

    Name  Age    City  Marks
1  Rohit   43    pune     78
2  Nitin   54   delhi     98
3    Ram   23    agra     96
4  Shyam   54   noida     85
5  Naman   65  devash     93

In [383]:
dt[dt['City']=='pune']

    Name  Age  City  Marks
1  Rohit   43  pune     78

In [384]:
dt[(dt['Age']>45)&(dt['Marks']>90)]

    Name  Age    City  Marks
2  Nitin   54   delhi     98
5  Naman   65  devash     93

In [385]:
dt[(dt['City']=='pune')|(dt['Marks']>90)]

    Name  Age    City  Marks
0   Amit   21  Indore     99
1  Rohit   43    pune     78
2  Nitin   54   delhi     98
3    Ram   23    agra     96
5  Naman   65  devash     93

In [386]:
df[df["Marks"] > 80]["Name"]

0    Aman
1    Riya
3    Neha
4    Aman
5    Amit
Name: Name, dtype: object

 Add, modify, delete and rename

In [387]:
#  Ek naya column add karna
df['Salary']=[98373,83434,75844,84844,64575,87696]

In [388]:
df

    Name  Age    City  Marks  Salary
0   Aman   21   Delhi     85   98373
1   Riya   22  Mumbai     92   83434
2  Kabir   20   Delhi     76   75844
3   Neha   23    Pune     88   84844
4   Aman   21   Delhi     85   64575
5   Amit   21  Indore     95   87696

In [389]:
#Same value ka column add karna
df["Country"]='India'

In [390]:
df

    Name  Age    City  Marks  Salary Country
0   Aman   21   Delhi     85   98373   India
1   Riya   22  Mumbai     92   83434   India
2  Kabir   20   Delhi     76   75844   India
3   Neha   23    Pune     88   84844   India
4   Aman   21   Delhi     85   64575   India
5   Amit   21  Indore     95   87696   India

In [391]:
#Existing column se new column banana

#Ye bahut important hai.

#Maan lo hume Marks ke basis par Pass/Fail banana hai.

df["Result"]=df["Marks"]>=80
df

    Name  Age    City  Marks  Salary Country  Result
0   Aman   21   Delhi     85   98373   India    True
1   Riya   22  Mumbai     92   83434   India    True
2  Kabir   20   Delhi     76   75844   India   False
3   Neha   23    Pune     88   84844   India    True
4   Aman   21   Delhi     85   64575   India    True
5   Amit   21  Indore     95   87696   India    True

MODIFY

Modify ka matlab:

Existing data ko change karna.

5️⃣ Ek particular cell modify karna

Maan lo Aman ke Marks 85 se 95 karne hain.

In [392]:
df.loc[0,'Marks']=81
df.loc[1,'Marks']=71
df.loc[3,'Marks']=60
df

    Name  Age    City  Marks  Salary Country  Result
0   Aman   21   Delhi     81   98373   India    True
1   Riya   22  Mumbai     71   83434   India    True
2  Kabir   20   Delhi     76   75844   India   False
3   Neha   23    Pune     60   84844   India    True
4   Aman   21   Delhi     85   64575   India    True
5   Amit   21  Indore     95   87696   India    True

In [393]:
# Puri column ko modify karna
# Maan lo sabke Marks me 5 add karne hain:


df["Marks"] = df["Marks"] + 5
df

    Name  Age    City  Marks  Salary Country  Result
0   Aman   21   Delhi     86   98373   India    True
1   Riya   22  Mumbai     76   83434   India    True
2  Kabir   20   Delhi     81   75844   India   False
3   Neha   23    Pune     65   84844   India    True
4   Aman   21   Delhi     90   64575   India    True
5   Amit   21  Indore    100   87696   India    True

Condition ke according modify

Maan lo:

Jinke Marks 80 se kam hain, unke Marks 10 badha do.

In [394]:
df.loc[df['Marks']>80,'Marks']+10

0     96
2     91
4    100
5    110
Name: Marks, dtype: int64

DELETE

Delete ke do main cases hain:

Column delete
Row delete
Column delete karna

Maan lo Salary delete karna hai:



drop() kya karta hai?

Data ko remove karta hai.

"Salary" kya hai?

Jise delete karna hai.

axis=1 kya hai?

Column delete karna hai.

axis=0 → Row,
axis=1 → Column

In [395]:
df.drop("Salary",axis=1,inplace=True)
df

    Name  Age    City  Marks Country  Result
0   Aman   21   Delhi     86   India    True
1   Riya   22  Mumbai     76   India    True
2  Kabir   20   Delhi     81   India   False
3   Neha   23    Pune     65   India    True
4   Aman   21   Delhi     90   India    True
5   Amit   21  Indore    100   India    True

In [396]:
#Row delete karna
#Maan lo index 2 wali row delete karni hai:

df.drop(2,axis=0,inplace=True)
df

   Name  Age    City  Marks Country  Result
0  Aman   21   Delhi     86   India    True
1  Riya   22  Mumbai     76   India    True
3  Neha   23    Pune     65   India    True
4  Aman   21   Delhi     90   India    True
5  Amit   21  Indore    100   India    True

RENAME

Rename ka matlab:

Naam change karna.

Ek column ka naam change

Marks ko Score karna hai:

In [397]:
df.rename(columns={'Marks':'Score'},inplace=True)
df

   Name  Age    City  Score Country  Result
0  Aman   21   Delhi     86   India    True
1  Riya   22  Mumbai     76   India    True
3  Neha   23    Pune     65   India    True
4  Aman   21   Delhi     90   India    True
5  Amit   21  Indore    100   India    True

In [398]:
df.rename(columns={
    'City':'Location',
    'Name':'Student name'
},inplace=True)
df

  Student name  Age Location  Score Country  Result
0         Aman   21    Delhi     86   India    True
1         Riya   22   Mumbai     76   India    True
3         Neha   23     Pune     65   India    True
4         Aman   21    Delhi     90   India    True
5         Amit   21   Indore    100   India    True

Sorting

Sorting ka matlab:

Data ko kisi column ke according order me arrange karna.,,,,,

sort_values() ka basic syntax\\\\\\\\
df.sort_values("column_name")

\\\\Default me ascending order hota hai.

####
Important point:

df.sort_values("Marks")

sirf sorted result return karta hai. Original df ko permanently change nahi karta.

Agar original DataFrame ko hi sort karna hai:

df.sort_values("Marks", inplace=True)

Ab df permanently sorted ho jayega.

#############
df = df.sort_values("Marks").reset_index(drop=True)
drop=True ka matlab:

Purane index ko new column mat banao.
###
ascending=True   → छोटा → बड़ा
ascending=False  → बड़ा → छोटा

In [399]:
df.sort_values('Score')

  Student name  Age Location  Score Country  Result
3         Neha   23     Pune     65   India    True
1         Riya   22   Mumbai     76   India    True
0         Aman   21    Delhi     86   India    True
4         Aman   21    Delhi     90   India    True
5         Amit   21   Indore    100   India    True

In [400]:
df.sort_values('Age',ascending=False,inplace=True)
df.reset_index(drop=True,inplace=True)
df

  Student name  Age Location  Score Country  Result
0         Neha   23     Pune     65   India    True
1         Riya   22   Mumbai     76   India    True
2         Aman   21    Delhi     86   India    True
3         Aman   21    Delhi     90   India    True
4         Amit   21   Indore    100   India    True

In [405]:
df.sort_values([
    'Score',
    'Student name'],ascending=True,inplace=True)
df.reset_index(drop=True,inplace=True)
df

  Student name  Age Location  Score Country  Result
0         Neha   23     Pune     65   India    True
1         Riya   22   Mumbai     76   India    True
2         Aman   21    Delhi     86   India    True
3         Aman   21    Delhi     90   India    True
4         Amit   21   Indore    100   India    True

#### Basic calculation ####

###############################

df["Marks"].sum()
df["Marks"].mean()
df["Marks"].median()
df["Marks"].min()
df["Marks"].max()
df["Marks"].std()
df["Marks"].var()
df["Marks"].count()

df["Marks"].add(5)
df["Marks"].sub(5)
df["Marks"].mul(2)
df["Marks"].div(2)

In [408]:


df['Score'].mean()

np.float64(83.4)

In [409]:
df['Score'].add(4)

0     69
1     80
2     90
3     94
4    104
Name: Score, dtype: int64

In [410]:
df['Score'].var()

179.8

In [411]:
df['Score'].max()

100

In [412]:
df['Score'].min()

65

In [414]:
df['Score'].std()

13.408952233489387

## Import and export

# CSV
df=pd.read_csv("data.csv")  ##### import krne ke liye

df.to_csv("output.csv",index=False)  ##### bapis se save krne ke liye(export)

# Excel
df=pd.read_excel("data.xlsx",sheet_name="Sheet1")

df.to_excel("output.xlsx",index=False)

# JSON
df=pd.read_json("data.json")

df.to_json("output.json",orient="records")