<a href="https://colab.research.google.com/github/amitsingh6261/my_all_python_Program/blob/main/Pandas_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [666]:
import pandas as pd
df=pd.read_csv('/content/Company_Employee_Data_Analysis_Project (1).csv')

In [667]:
df

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
0,1001,Employee_001,28,Sales,Mumbai,1,39441,89,88,8,2026
1,1002,Employee_002,25,Marketing,Bengaluru,2,49388,55,84,4,2026
2,1003,Employee_003,27,Finance,Bengaluru,1,37069,94,87,1,2025
3,1004,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026
4,1005,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024
...,...,...,...,...,...,...,...,...,...,...,...
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015
196,1197,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025
198,1199,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022
199,1200,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025

# Level 1 — Data Understanding
.Dataset me total kitne employees aur columns hain?

.Saare column names batao.

.Dataset ki basic information nikalo.

.Numerical columns ka statistical summary nikalo.

In [668]:
df.head()

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
0,1001,Employee_001,28,Sales,Mumbai,1,39441,89,88,8,2026
1,1002,Employee_002,25,Marketing,Bengaluru,2,49388,55,84,4,2026
2,1003,Employee_003,27,Finance,Bengaluru,1,37069,94,87,1,2025
3,1004,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026
4,1005,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024

In [669]:
df.tail()

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015
196,1197,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025
198,1199,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022
199,1200,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025

In [670]:
df.shape

(200, 11)

In [671]:
df.dtypes

Employee_ID            int64
Name                  object
Age                    int64
Department            object
City                  object
Experience_Years       int64
Monthly_Salary         int64
Performance_Score      int64
Attendance_Percent     int64
Projects_Completed     int64
Joining_Year           int64
dtype: object

In [672]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         200 non-null    int64
 1   Name                200 non-null    object
 2   Age                 200 non-null    int64
 3   Department          200 non-null    object
 4   City                200 non-null    object
 5   Experience_Years    200 non-null    int64
 6   Monthly_Salary      200 non-null    int64
 7   Performance_Score   200 non-null    int64
 8   Attendance_Percent  200 non-null    int64
 9   Projects_Completed  200 non-null    int64
 10  Joining_Year        200 non-null    int64
dtypes: int64(8), object(3)
memory usage: 17.3+ KB

In [673]:
df.describe()

,Employee_ID,Age,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,1100.500000,33.660000,5.730000,64393.470000,78.350000,84.700000,4.405000,2023.295000
std,57.879185,6.950247,5.645926,25827.132452,12.981142,9.016456,2.359835,3.640638
min,1001.000000,22.000000,0.000000,28117.000000,55.000000,70.000000,1.000000,2009.000000
25%,1050.750000,28.000000,1.000000,45435.750000,67.000000,77.000000,2.000000,2022.000000
50%,1100.500000,34.000000,4.000000,54558.500000,80.000000,86.000000,4.000000,2025.000000
75%,1150.250000,40.000000,9.000000,78044.750000,90.000000,92.000000,7.000000,2026.000000
max,1200.000000,45.000000,22.000000,151295.000000,100.000000,100.000000,8.000000,2026.000000

In [674]:
df.describe(include='all')

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
count,200.000000,200,200.000000,200,200,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
unique,NaN,200,NaN,5,6,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Employee_001,NaN,Sales,Delhi,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,49,39,NaN,NaN,NaN,NaN,NaN,NaN
mean,1100.500000,NaN,33.660000,NaN,NaN,5.730000,64393.470000,78.350000,84.700000,4.405000,2023.295000
std,57.879185,NaN,6.950247,NaN,NaN,5.645926,25827.132452,12.981142,9.016456,2.359835,3.640638
min,1001.000000,NaN,22.000000,NaN,NaN,0.000000,28117.000000,55.000000,70.000000,1.000000,2009.000000
25%,1050.750000,NaN,28.000000,NaN,NaN,1.000000,45435.750000,67.000000,77.000000,2.000000,2022.000000
50%,1100.500000,NaN,34.000000,NaN,NaN,4.000000,54558.500000,80.000000,86.000000,4.000000,2025.000000
75%,1150.250000,NaN,40.000000,NaN,NaN,9.000000,78044.750000,90.000000,92.000000,7.000000,2026.000000
max,1200.000000,NaN,45.000000,NaN,NaN,22.000000,151295.000000,100.000000,100.000000,8.000000,2026.000000

In [675]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'City', 'Experience_Years',
       'Monthly_Salary', 'Performance_Score', 'Attendance_Percent',
       'Projects_Completed', 'Joining_Year'],
      dtype='object')

# Level 2 - Filtering

.₹60,000 se zyada salary wale employees nikalo.

.IT department ke employees nikalo.

.5+ years experience wale employees nikalo.

.Performance score 80+ wale employees nikalo.

.Bhopal ke employees jinki salary ₹50,000+ hai, unhe nikalo.

.IT department ke employees jinki performance 85+ hai.

In [676]:
df[df['Monthly_Salary']>60000]

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
5,1006,Employee_006,36,HR,Delhi,12,76254,62,97,8,2014
7,1008,Employee_008,44,Finance,Bhopal,5,69714,95,87,6,2021
9,1010,Employee_010,41,Marketing,Indore,7,67683,68,75,7,2025
10,1011,Employee_011,37,Sales,Bhopal,15,86738,84,88,7,2023
11,1012,Employee_012,34,Finance,Pune,12,76090,89,100,8,2025
...,...,...,...,...,...,...,...,...,...,...,...
190,1191,Employee_191,31,HR,Bengaluru,3,69537,83,88,8,2025
191,1192,Employee_192,33,Marketing,Bhopal,9,71719,99,90,4,2020
192,1193,Employee_193,38,Sales,Pune,16,84235,83,73,7,2023
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015
198,1199,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022

In [677]:
df[df['Department']=='IT']

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
18,1019,Employee_019,44,IT,Bhopal,3,39166,58,72,4,2025
23,1024,Employee_024,33,IT,Mumbai,6,72954,72,71,4,2026
24,1025,Employee_025,42,IT,Delhi,9,81008,94,97,3,2019
33,1034,Employee_034,42,IT,Pune,19,122193,69,70,2,2016
38,1039,Employee_039,43,IT,Delhi,6,72321,56,92,1,2021
41,1042,Employee_042,33,IT,Bengaluru,12,75240,94,98,5,2025
45,1046,Employee_046,43,IT,Bhopal,20,151295,57,84,1,2023
55,1056,Employee_056,37,IT,Bhopal,4,50150,90,93,6,2024
70,1071,Employee_071,22,IT,Mumbai,1,33031,67,87,7,2026
76,1077,Employee_077,45,IT,Delhi,3,52003,83,90,8,2026
81,1082,Employee_082,41,IT,Pune,3,63789,66,73,5,2025
84,1085,Employee_085,39,IT,Delhi,8,85926,81,87,6,2026
85,1086,Employee_086,24,IT,Pune,0,34229,85,71,8,2026
86,1087,Employee_087,22,IT,Bhopal,0,52025,90,70,1,2026
87,1088,Employee_088,22,IT,Bhopal,1,48009,90,84,2,2025
91,1092,Employee_092,33,IT,Bengaluru,12,114243,59,79,3,2019
94,1095,Employee_095,22,IT,Indore,0,35561,64,72,5,2026
99,1100,Employee_100,34,IT,Mumbai,8,62371,77,74,8,2025
101,1102,Employee_102,35,IT,Bengaluru,9,85569,100,75,1,2018
104,1105,Employee_105,39,IT,Delhi,12,77943,80,71,5,2016
110,1111,Employee_111,23,IT,Bhopal,1,33972,94,91,5,2026
114,1115,Employee_115,25,IT,Pune,4,52167,90,79,8,2026
118,1119,Employee_119,32,IT,Indore,0,53888,62,83,7,2026
124,1125,Employee_125,26,IT,Indore,5,52267,68,83,7,2025
140,1141,Employee_141,44,IT,Mumbai,8,78350,69,82,5,2019
150,1151,Employee_151,34,IT,Delhi,6,59954,65,78,1,2024
151,1152,Employee_152,40,IT,Delhi,1,45203,92,75,4,2026
152,1153,Employee_153,38,IT,Delhi,2,50385,56,71,5,2026
153,1154,Employee_154,25,IT,Bhopal,2,48746,61,86,6,2026
155,1156,Employee_156,30,IT,Indore,0,34469,81,94,5,2026
158,1159,Employee_159,30,IT,Bhopal,8,92976,71,81,8,2019
161,1162,Employee_162,41,IT,Indore,14,116001,78,79,4,2026
163,1164,Employee_164,36,IT,Mumbai,4,43828,61,90,2,2024
168,1169,Employee_169,33,IT,Delhi,6,69128,97,96,6,2026
170,1171,Employee_171,42,IT,Bengaluru,1,48144,80,71,7,2025
171,1172,Employee_172,25,IT,Pune,1,53922,82,81,5,2025
177,1178,Employee_178,42,IT,Bhopal,1,59789,74,82,3,2026
179,1180,Employee_180,28,IT,Mumbai,0,36512,82,95,6,2026
180,1181,Employee_181,35,IT,Bengaluru,5,46842,94,90,4,2025
182,1183,Employee_183,24,IT,Bengaluru,3,57716,55,99,6,2026
187,1188,Employee_188,36,IT,Pune,2,38490,73,91,4,2024
188,1189,Employee_189,33,IT,Mumbai,0,37310,86,80,1,2026
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025

In [678]:
df[df['Experience_Years']>5]

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
5,1006,Employee_006,36,HR,Delhi,12,76254,62,97,8,2014
9,1010,Employee_010,41,Marketing,Indore,7,67683,68,75,7,2025
10,1011,Employee_011,37,Sales,Bhopal,15,86738,84,88,7,2023
11,1012,Employee_012,34,Finance,Pune,12,76090,89,100,8,2025
14,1015,Employee_015,40,Sales,Pune,19,118571,59,77,5,2022
...,...,...,...,...,...,...,...,...,...,...,...
186,1187,Employee_187,39,Marketing,Delhi,9,86114,77,97,5,2017
191,1192,Employee_192,33,Marketing,Bhopal,9,71719,99,90,4,2020
192,1193,Employee_193,38,Sales,Pune,16,84235,83,73,7,2023
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025

In [679]:
df[df['Performance_Score']>80]

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
0,1001,Employee_001,28,Sales,Mumbai,1,39441,89,88,8,2026
2,1003,Employee_003,27,Finance,Bengaluru,1,37069,94,87,1,2025
4,1005,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024
7,1008,Employee_008,44,Finance,Bhopal,5,69714,95,87,6,2021
8,1009,Employee_009,29,Finance,Bengaluru,2,42350,91,99,2,2025
...,...,...,...,...,...,...,...,...,...,...,...
190,1191,Employee_191,31,HR,Bengaluru,3,69537,83,88,8,2025
191,1192,Employee_192,33,Marketing,Bhopal,9,71719,99,90,4,2020
192,1193,Employee_193,38,Sales,Pune,16,84235,83,73,7,2023
193,1194,Employee_194,27,HR,Indore,1,41661,84,88,1,2025
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015

In [680]:
df[(df['City']=='Bhopal') & (df['Monthly_Salary']>50000)]

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
7,1008,Employee_008,44,Finance,Bhopal,5,69714,95,87,6,2021
10,1011,Employee_011,37,Sales,Bhopal,15,86738,84,88,7,2023
13,1014,Employee_014,31,HR,Bhopal,5,67915,91,70,6,2021
15,1016,Employee_016,38,HR,Bhopal,16,129415,73,98,8,2011
17,1018,Employee_018,40,Marketing,Bhopal,12,106034,80,76,2,2022
25,1026,Employee_026,22,Finance,Bhopal,1,53469,62,70,1,2025
32,1033,Employee_033,34,Sales,Bhopal,11,85277,77,77,2,2022
45,1046,Employee_046,43,IT,Bhopal,20,151295,57,84,1,2023
48,1049,Employee_049,36,HR,Bhopal,11,80678,96,88,3,2023
49,1050,Employee_050,38,Sales,Bhopal,12,92195,69,70,2,2014
50,1051,Employee_051,35,Sales,Bhopal,12,70302,83,97,5,2021
55,1056,Employee_056,37,IT,Bhopal,4,50150,90,93,6,2024
61,1062,Employee_062,44,Sales,Bhopal,17,92121,87,73,3,2010
64,1065,Employee_065,26,HR,Bhopal,5,50626,56,91,5,2022
72,1073,Employee_073,26,Marketing,Bhopal,5,68833,90,79,6,2024
82,1083,Employee_083,45,Marketing,Bhopal,21,102562,99,98,6,2009
86,1087,Employee_087,22,IT,Bhopal,0,52025,90,70,1,2026
95,1096,Employee_096,29,Finance,Bhopal,5,53758,94,92,2,2026
97,1098,Employee_098,32,HR,Bhopal,2,61732,60,81,8,2025
98,1099,Employee_099,33,HR,Bhopal,4,68734,62,89,2,2022
108,1109,Employee_109,29,Finance,Bhopal,5,52238,79,89,6,2024
120,1121,Employee_121,25,HR,Bhopal,0,54900,82,86,2,2026
128,1129,Employee_129,38,Marketing,Bhopal,4,62119,65,82,2,2024
135,1136,Employee_136,45,Finance,Bhopal,9,68611,100,83,4,2022
141,1142,Employee_142,34,Marketing,Bhopal,13,115105,75,71,3,2014
146,1147,Employee_147,38,Sales,Bhopal,16,131077,95,87,4,2024
158,1159,Employee_159,30,IT,Bhopal,8,92976,71,81,8,2019
177,1178,Employee_178,42,IT,Bhopal,1,59789,74,82,3,2026
191,1192,Employee_192,33,Marketing,Bhopal,9,71719,99,90,4,2020

In [681]:
df[(df['Department']=='IT') & (df['Performance_Score']>85)]

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year
24,1025,Employee_025,42,IT,Delhi,9,81008,94,97,3,2019
41,1042,Employee_042,33,IT,Bengaluru,12,75240,94,98,5,2025
55,1056,Employee_056,37,IT,Bhopal,4,50150,90,93,6,2024
86,1087,Employee_087,22,IT,Bhopal,0,52025,90,70,1,2026
87,1088,Employee_088,22,IT,Bhopal,1,48009,90,84,2,2025
101,1102,Employee_102,35,IT,Bengaluru,9,85569,100,75,1,2018
110,1111,Employee_111,23,IT,Bhopal,1,33972,94,91,5,2026
114,1115,Employee_115,25,IT,Pune,4,52167,90,79,8,2026
151,1152,Employee_152,40,IT,Delhi,1,45203,92,75,4,2026
168,1169,Employee_169,33,IT,Delhi,6,69128,97,96,6,2026
180,1181,Employee_181,35,IT,Bengaluru,5,46842,94,90,4,2025
188,1189,Employee_189,33,IT,Mumbai,0,37310,86,80,1,2026

# Level 3 — Add & Modify
.Salary_Level naam ka column banao.

.Salary >= 60000 → "High"


.Salary < 60000 → "Normal"

.Performance_Level column banao.

.Kisi specific employee ki salary modify karo.

.Kisi condition ke according data modify karo.

In [682]:
df['Salary_Level']='Normal'

In [683]:
df

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level
0,1001,Employee_001,28,Sales,Mumbai,1,39441,89,88,8,2026,Normal
1,1002,Employee_002,25,Marketing,Bengaluru,2,49388,55,84,4,2026,Normal
2,1003,Employee_003,27,Finance,Bengaluru,1,37069,94,87,1,2025,Normal
3,1004,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026,Normal
4,1005,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015,Normal
196,1197,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024,Normal
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025,Normal
198,1199,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022,Normal
199,1200,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025,Normal

In [684]:
df.loc[df['Monthly_Salary']>=60000, 'Salary_Level']="High"
df

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level
0,1001,Employee_001,28,Sales,Mumbai,1,39441,89,88,8,2026,Normal
1,1002,Employee_002,25,Marketing,Bengaluru,2,49388,55,84,4,2026,Normal
2,1003,Employee_003,27,Finance,Bengaluru,1,37069,94,87,1,2025,Normal
3,1004,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026,Normal
4,1005,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015,High
196,1197,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024,Normal
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025,Normal
198,1199,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022,High
199,1200,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025,Normal

In [685]:
df['Performance_Level']='Average'
df.loc[df['Performance_Score']>75,'Performance_Level']='Good'

In [686]:
df

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level,Performance_Level
0,1001,Employee_001,28,Sales,Mumbai,1,39441,89,88,8,2026,Normal,Good
1,1002,Employee_002,25,Marketing,Bengaluru,2,49388,55,84,4,2026,Normal,Average
2,1003,Employee_003,27,Finance,Bengaluru,1,37069,94,87,1,2025,Normal,Good
3,1004,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026,Normal,Good
4,1005,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024,Normal,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015,High,Good
196,1197,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024,Normal,Average
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025,Normal,Average
198,1199,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022,High,Average
199,1200,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025,Normal,Average

In [687]:
df.loc[df['Employee_ID']==1001,'Monthly_Salary']=55000
df

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level,Performance_Level
0,1001,Employee_001,28,Sales,Mumbai,1,55000,89,88,8,2026,Normal,Good
1,1002,Employee_002,25,Marketing,Bengaluru,2,49388,55,84,4,2026,Normal,Average
2,1003,Employee_003,27,Finance,Bengaluru,1,37069,94,87,1,2025,Normal,Good
3,1004,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026,Normal,Good
4,1005,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024,Normal,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015,High,Good
196,1197,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024,Normal,Average
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025,Normal,Average
198,1199,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022,High,Average
199,1200,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025,Normal,Average

In [688]:
df.loc[df['Age']<=28,'Age']+=5
df

,Employee_ID,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level,Performance_Level
0,1001,Employee_001,33,Sales,Mumbai,1,55000,89,88,8,2026,Normal,Good
1,1002,Employee_002,30,Marketing,Bengaluru,2,49388,55,84,4,2026,Normal,Average
2,1003,Employee_003,32,Finance,Bengaluru,1,37069,94,87,1,2025,Normal,Good
3,1004,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026,Normal,Good
4,1005,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024,Normal,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1196,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015,High,Good
196,1197,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024,Normal,Average
197,1198,Employee_198,29,IT,Pune,7,57756,72,80,7,2025,Normal,Average
198,1199,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022,High,Average
199,1200,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025,Normal,Average

# Level 4 — Delete & Rename
.Ek unnecessary column delete karo.

.Name ko Employee_Name rename karo.

.Monthly_Salary ko Salary rename karo.

In [689]:
df.drop('Employee_ID',axis=1,inplace=True)
df

,Name,Age,Department,City,Experience_Years,Monthly_Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level,Performance_Level
0,Employee_001,33,Sales,Mumbai,1,55000,89,88,8,2026,Normal,Good
1,Employee_002,30,Marketing,Bengaluru,2,49388,55,84,4,2026,Normal,Average
2,Employee_003,32,Finance,Bengaluru,1,37069,94,87,1,2025,Normal,Good
3,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026,Normal,Good
4,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024,Normal,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
195,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015,High,Good
196,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024,Normal,Average
197,Employee_198,29,IT,Pune,7,57756,72,80,7,2025,Normal,Average
198,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022,High,Average
199,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025,Normal,Average

In [690]:
df.rename(columns={
    'Name':"Employee_Name",
    'Monthly_Salary':'Salary'
},inplace=True)
df

,Employee_Name,Age,Department,City,Experience_Years,Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level,Performance_Level
0,Employee_001,33,Sales,Mumbai,1,55000,89,88,8,2026,Normal,Good
1,Employee_002,30,Marketing,Bengaluru,2,49388,55,84,4,2026,Normal,Average
2,Employee_003,32,Finance,Bengaluru,1,37069,94,87,1,2025,Normal,Good
3,Employee_004,34,Marketing,Bhopal,1,35800,76,71,3,2026,Normal,Good
4,Employee_005,41,Marketing,Delhi,4,54015,83,91,7,2024,Normal,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
195,Employee_196,35,Finance,Indore,11,75067,94,98,6,2015,High,Good
196,Employee_197,34,Finance,Pune,3,42030,73,90,1,2024,Normal,Average
197,Employee_198,29,IT,Pune,7,57756,72,80,7,2025,Normal,Average
198,Employee_199,31,Marketing,Pune,4,61019,55,77,7,2022,High,Average
199,Employee_200,30,Sales,Indore,1,39662,68,80,4,2025,Normal,Average

# Level 5 — Sorting
.Salary ko highest → lowest sort karo.

.Experience ko highest → lowest sort karo.

In [691]:
df.sort_values(
    ["Salary", "Experience_Years",],
    ascending=[False, False],
    inplace=True
)
df

,Employee_Name,Age,Department,City,Experience_Years,Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level,Performance_Level
45,Employee_046,43,IT,Bhopal,20,151295,57,84,1,2023,High,Average
146,Employee_147,38,Sales,Bhopal,16,131077,95,87,4,2024,High,Good
63,Employee_064,43,HR,Delhi,16,130391,76,74,1,2021,High,Good
15,Employee_016,38,HR,Bhopal,16,129415,73,98,8,2011,High,Average
136,Employee_137,44,Sales,Mumbai,18,129110,90,73,4,2014,High,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
65,Employee_066,30,Sales,Delhi,0,33122,64,90,1,2026,Normal,Average
70,Employee_071,27,IT,Mumbai,1,33031,67,87,7,2026,Normal,Average
194,Employee_195,33,Sales,Delhi,0,29908,70,95,2,2026,Normal,Average
122,Employee_123,30,Marketing,Delhi,0,29605,63,88,6,2026,Normal,Average
142,Employee_143,44,Sales,Bengaluru,0,28117,63,92,8,2026,Normal,Average

In [692]:
df.to_csv("/content/final_employee_report.csv",index=False)
df

,Employee_Name,Age,Department,City,Experience_Years,Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level,Performance_Level
45,Employee_046,43,IT,Bhopal,20,151295,57,84,1,2023,High,Average
146,Employee_147,38,Sales,Bhopal,16,131077,95,87,4,2024,High,Good
63,Employee_064,43,HR,Delhi,16,130391,76,74,1,2021,High,Good
15,Employee_016,38,HR,Bhopal,16,129415,73,98,8,2011,High,Average
136,Employee_137,44,Sales,Mumbai,18,129110,90,73,4,2014,High,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
65,Employee_066,30,Sales,Delhi,0,33122,64,90,1,2026,Normal,Average
70,Employee_071,27,IT,Mumbai,1,33031,67,87,7,2026,Normal,Average
194,Employee_195,33,Sales,Delhi,0,29908,70,95,2,2026,Normal,Average
122,Employee_123,30,Marketing,Delhi,0,29605,63,88,6,2026,Normal,Average
142,Employee_143,44,Sales,Bengaluru,0,28117,63,92,8,2026,Normal,Average

In [693]:
## After Analylis Data is....

In [694]:
pd.read_csv('/content/final_employee_report.csv')

,Employee_Name,Age,Department,City,Experience_Years,Salary,Performance_Score,Attendance_Percent,Projects_Completed,Joining_Year,Salary_Level,Performance_Level
0,Employee_046,43,IT,Bhopal,20,151295,57,84,1,2023,High,Average
1,Employee_147,38,Sales,Bhopal,16,131077,95,87,4,2024,High,Good
2,Employee_064,43,HR,Delhi,16,130391,76,74,1,2021,High,Good
3,Employee_016,38,HR,Bhopal,16,129415,73,98,8,2011,High,Average
4,Employee_137,44,Sales,Mumbai,18,129110,90,73,4,2014,High,Good
...,...,...,...,...,...,...,...,...,...,...,...,...
195,Employee_066,30,Sales,Delhi,0,33122,64,90,1,2026,Normal,Average
196,Employee_071,27,IT,Mumbai,1,33031,67,87,7,2026,Normal,Average
197,Employee_195,33,Sales,Delhi,0,29908,70,95,2,2026,Normal,Average
198,Employee_123,30,Marketing,Delhi,0,29605,63,88,6,2026,Normal,Average
199,Employee_143,44,Sales,Bengaluru,0,28117,63,92,8,2026,Normal,Average