<a href="https://colab.research.google.com/github/amitsingh6261/my_all_python_Program/blob/main/Pandas_Cleaning_%26_Transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Definition
Data cleaning and Transformation in pandas is the process of removing error,missing or duplicate data and changing tha data into a proper and useful format for analylis.

In [95]:
import pandas as pd
df=pd.read_csv('/content/pandas_data_cleaning_1000.csv')

In [96]:
df

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,1001,Arjun,20.0,Pune,Finance,5.0,49519.0,66.6,4.0,2015.0
1,1002,Neha,34.0,Bhopal,Marketing,0.0,47439.0,71.9,9.0,2020.0
2,1003,Simran,27.0,Indore,HR,19.0,101949.0,92.4,8.0,2016.0
3,1004,Rahul,30.0,Mumbai,Sales,15.0,39995.0,99.7,9.0,2020.0
4,1005,Arjun,NaN,Jaipur,Marketing,14.0,48559.0,75.0,4.0,2024.0
...,...,...,...,...,...,...,...,...,...,...
1000,1011,Neha,43.0,Mumbai,Marketing,14.0,64350.0,80.9,5.0,2026.0
1001,1026,Aman,20.0,Mumbai,Sales,3.0,89418.0,57.1,6.0,2021.0
1002,1051,Kabir,45.0,Jaipur,Finance,19.0,108014.0,93.9,2.0,2020.0
1003,1076,Anjali,36.0,Mumbai,IT,5.0,40408.0,47.2,2.0,2017.0
1004,1101,Riya,32.0,Kolkata,Sales,13.0,70541.0,49.1,6.0,2023.0

In [97]:
# df.isnull() DataFrame ke har cell mein check karta hai ki value missing hai ya nahi. ans true false me deta hai

df.isnull()

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1000,False,False,False,False,False,False,False,False,False,False
1001,False,False,False,False,False,False,False,False,False,False
1002,False,False,False,False,False,False,False,False,False,False
1003,False,False,False,False,False,False,False,False,False,False
1004,False,False,False,False,False,False,False,False,False,False

In [98]:
# df.isna() ka kaam exactly df.isnull() jaisa hi hai.

df.isna()

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
1000,False,False,False,False,False,False,False,False,False,False
1001,False,False,False,False,False,False,False,False,False,False
1002,False,False,False,False,False,False,False,False,False,False
1003,False,False,False,False,False,False,False,False,False,False
1004,False,False,False,False,False,False,False,False,False,False

In [99]:
# Har column mein kitni missing values hain, ye batata hai.
df.isnull().sum()

ID                    0
Name                  0
Age                  50
City                 30
Department            0
Experience_Years     40
Salary               40
Performance_Score    30
Projects              0
Joining_Year          0
dtype: int64

In [100]:
df.isna().sum()

ID                    0
Name                  0
Age                  50
City                 30
Department            0
Experience_Years     40
Salary               40
Performance_Score    30
Projects              0
Joining_Year          0
dtype: int64

In [101]:
# df.isnull().sum().sum()

#Ye poore DataFrame ki total missing values count karega

In [102]:
df.isnull().sum().sum()

np.int64(190)

In [103]:
# df[df.isnull().any(axis=1)]
#Jis row mein kam se kam ek missing value hai, woh poori row dikhata hai.

df[df.isnull().any(axis=1)]

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
4,1005,Arjun,NaN,Jaipur,Marketing,14.0,48559.0,75.0,4.0,2024.0
8,1009,Simran,23.0,Bhopal,Finance,NaN,76539.0,64.2,5.0,2023.0
13,1014,Kabir,29.0,NaN,HR,4.0,103653.0,77.9,4.0,2021.0
17,1018,Simran,NaN,Bhopal,Marketing,0.0,114132.0,82.0,9.0,2020.0
32,1033,Rahul,41.0,Jaipur,Finance,10.0,NaN,46.5,10.0,2024.0
...,...,...,...,...,...,...,...,...,...,...
960,1961,Vikas,23.0,Pune,HR,NaN,31638.0,46.0,9.0,2025.0
965,1966,Neha,29.0,Pune,Marketing,NaN,107291.0,44.8,6.0,2016.0
966,1967,Priya,22.0,NaN,Sales,18.0,48382.0,81.0,8.0,2021.0
986,1987,Anjali,24.0,Indore,HR,11.0,59753.0,NaN,6.0,2024.0
993,1994,Simran,43.0,Delhi,Marketing,1.0,57467.0,NaN,6.0,2025.0

In [104]:
df[df['Salary'].isna()]

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
32,1033,Rahul,41.0,Jaipur,Finance,10.0,NaN,46.5,10.0,2024.0
69,1070,Vikas,26.0,Jaipur,HR,10.0,NaN,63.8,6.0,2016.0
117,1118,Arjun,20.0,NaN,IT,5.0,NaN,88.2,6.0,2020.0
123,1124,Arjun,29.0,Indore,Finance,11.0,NaN,57.8,5.0,2025.0
128,1129,Arjun,42.0,Indore,IT,5.0,NaN,44.8,4.0,2026.0
142,1143,Vikas,34.0,Jaipur,Marketing,7.0,NaN,98.3,3.0,2015.0
146,1147,Vikas,20.0,Bhopal,Marketing,3.0,NaN,64.3,4.0,2021.0
152,1153,Priya,33.0,Lucknow,Finance,19.0,NaN,88.6,4.0,2021.0
168,1169,Arjun,26.0,Kolkata,Marketing,4.0,NaN,66.6,0.0,2020.0
197,1198,Neha,22.0,Kolkata,Sales,3.0,NaN,51.1,3.0,2026.0
208,1209,Anjali,36.0,Pune,Sales,4.0,NaN,43.7,0.0,2018.0
219,1220,Simran,28.0,Lucknow,Sales,2.0,NaN,72.5,6.0,2022.0
269,1270,Rahul,30.0,Indore,HR,9.0,NaN,89.8,3.0,2015.0
295,1296,Aman,45.0,Bhopal,Sales,3.0,NaN,49.5,0.0,2017.0
304,1305,Kabir,32.0,Indore,Marketing,9.0,NaN,65.1,10.0,2022.0
309,1310,Aman,21.0,Indore,Finance,9.0,NaN,68.3,5.0,2023.0
368,1369,Rahul,36.0,Jaipur,HR,5.0,NaN,50.3,1.0,2019.0
370,1371,Neha,45.0,Kolkata,Finance,16.0,NaN,52.8,1.0,2025.0
384,1385,Arjun,42.0,Jaipur,Finance,15.0,NaN,79.8,6.0,2025.0
420,1421,Neha,31.0,Indore,Sales,15.0,NaN,70.3,0.0,2016.0
424,1425,Anjali,29.0,Mumbai,IT,1.0,NaN,NaN,3.0,2026.0
425,1426,Anjali,21.0,Indore,Marketing,14.0,NaN,53.9,1.0,2022.0
436,1437,Simran,31.0,Jaipur,Finance,17.0,NaN,97.4,7.0,2017.0
486,1487,Aman,23.0,Delhi,IT,3.0,NaN,51.4,3.0,2020.0
505,1506,Priya,24.0,Pune,Finance,16.0,NaN,97.7,9.0,2019.0
510,1511,Kabir,NaN,Indore,Sales,9.0,NaN,96.5,5.0,2021.0
538,1539,Anjali,28.0,Pune,Sales,7.0,NaN,65.1,8.0,2017.0
558,1559,Vikas,NaN,Jaipur,IT,17.0,NaN,47.2,10.0,2026.0
573,1574,Simran,27.0,Delhi,IT,18.0,NaN,43.2,2.0,2024.0
576,1577,Aman,32.0,Bhopal,Marketing,16.0,NaN,63.5,9.0,2017.0
586,1587,Anjali,28.0,Indore,Finance,20.0,NaN,67.6,4.0,2025.0
593,1594,Kabir,23.0,Bhopal,HR,10.0,NaN,99.5,9.0,2015.0
690,1691,Aman,22.0,Bhopal,Sales,9.0,NaN,NaN,9.0,2021.0
743,1744,Kabir,39.0,Bhopal,HR,0.0,NaN,95.0,1.0,2023.0
763,1764,Vikas,33.0,Delhi,Sales,17.0,NaN,61.1,7.0,2017.0
776,1777,Neha,43.0,Pune,Marketing,12.0,NaN,88.3,7.0,2026.0
800,1801,Aman,45.0,Jaipur,Marketing,3.0,NaN,71.5,0.0,2021.0
822,1823,Rahul,28.0,Indore,IT,NaN,NaN,44.1,3.0,2022.0
916,1917,Kabir,32.0,Bhopal,Marketing,2.0,NaN,74.6,2.0,2018.0
946,1947,Kabir,21.0,Bhopal,Marketing,20.0,NaN,85.5,8.0,2018.0

In [105]:
# Salary ka median use karke jaha missing value hogi waha fill kar dega.
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,1001,Arjun,20.0,Pune,Finance,5.0,49519.0,66.6,4.0,2015.0
1,1002,Neha,34.0,Bhopal,Marketing,0.0,47439.0,71.9,9.0,2020.0
2,1003,Simran,27.0,Indore,HR,19.0,101949.0,92.4,8.0,2016.0
3,1004,Rahul,30.0,Mumbai,Sales,15.0,39995.0,99.7,9.0,2020.0
4,1005,Arjun,NaN,Jaipur,Marketing,14.0,48559.0,75.0,4.0,2024.0
...,...,...,...,...,...,...,...,...,...,...
1000,1011,Neha,43.0,Mumbai,Marketing,14.0,64350.0,80.9,5.0,2026.0
1001,1026,Aman,20.0,Mumbai,Sales,3.0,89418.0,57.1,6.0,2021.0
1002,1051,Kabir,45.0,Jaipur,Finance,19.0,108014.0,93.9,2.0,2020.0
1003,1076,Anjali,36.0,Mumbai,IT,5.0,40408.0,47.2,2.0,2017.0
1004,1101,Riya,32.0,Kolkata,Sales,13.0,70541.0,49.1,6.0,2023.0

In [106]:
df.isnull().sum()

ID                    0
Name                  0
Age                  50
City                 30
Department            0
Experience_Years     40
Salary                0
Performance_Score    30
Projects              0
Joining_Year          0
dtype: int64

In [107]:
df['City']=df['City'].fillna('Unknown')
df

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,1001,Arjun,20.0,Pune,Finance,5.0,49519.0,66.6,4.0,2015.0
1,1002,Neha,34.0,Bhopal,Marketing,0.0,47439.0,71.9,9.0,2020.0
2,1003,Simran,27.0,Indore,HR,19.0,101949.0,92.4,8.0,2016.0
3,1004,Rahul,30.0,Mumbai,Sales,15.0,39995.0,99.7,9.0,2020.0
4,1005,Arjun,NaN,Jaipur,Marketing,14.0,48559.0,75.0,4.0,2024.0
...,...,...,...,...,...,...,...,...,...,...
1000,1011,Neha,43.0,Mumbai,Marketing,14.0,64350.0,80.9,5.0,2026.0
1001,1026,Aman,20.0,Mumbai,Sales,3.0,89418.0,57.1,6.0,2021.0
1002,1051,Kabir,45.0,Jaipur,Finance,19.0,108014.0,93.9,2.0,2020.0
1003,1076,Anjali,36.0,Mumbai,IT,5.0,40408.0,47.2,2.0,2017.0
1004,1101,Riya,32.0,Kolkata,Sales,13.0,70541.0,49.1,6.0,2023.0

In [108]:
df.isnull().sum()

ID                    0
Name                  0
Age                  50
City                  0
Department            0
Experience_Years     40
Salary                0
Performance_Score    30
Projects              0
Joining_Year          0
dtype: int64

In [109]:
df['Age']=df['Age'].fillna(df['Age'].median())
df

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,1001,Arjun,20.0,Pune,Finance,5.0,49519.0,66.6,4.0,2015.0
1,1002,Neha,34.0,Bhopal,Marketing,0.0,47439.0,71.9,9.0,2020.0
2,1003,Simran,27.0,Indore,HR,19.0,101949.0,92.4,8.0,2016.0
3,1004,Rahul,30.0,Mumbai,Sales,15.0,39995.0,99.7,9.0,2020.0
4,1005,Arjun,33.0,Jaipur,Marketing,14.0,48559.0,75.0,4.0,2024.0
...,...,...,...,...,...,...,...,...,...,...
1000,1011,Neha,43.0,Mumbai,Marketing,14.0,64350.0,80.9,5.0,2026.0
1001,1026,Aman,20.0,Mumbai,Sales,3.0,89418.0,57.1,6.0,2021.0
1002,1051,Kabir,45.0,Jaipur,Finance,19.0,108014.0,93.9,2.0,2020.0
1003,1076,Anjali,36.0,Mumbai,IT,5.0,40408.0,47.2,2.0,2017.0
1004,1101,Riya,32.0,Kolkata,Sales,13.0,70541.0,49.1,6.0,2023.0

In [110]:
df.isnull().sum()

ID                    0
Name                  0
Age                   0
City                  0
Department            0
Experience_Years     40
Salary                0
Performance_Score    30
Projects              0
Joining_Year          0
dtype: int64

In [111]:
df['Performance_Score']=df['Performance_Score'].fillna(df['Performance_Score'].median())
df

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,1001,Arjun,20.0,Pune,Finance,5.0,49519.0,66.6,4.0,2015.0
1,1002,Neha,34.0,Bhopal,Marketing,0.0,47439.0,71.9,9.0,2020.0
2,1003,Simran,27.0,Indore,HR,19.0,101949.0,92.4,8.0,2016.0
3,1004,Rahul,30.0,Mumbai,Sales,15.0,39995.0,99.7,9.0,2020.0
4,1005,Arjun,33.0,Jaipur,Marketing,14.0,48559.0,75.0,4.0,2024.0
...,...,...,...,...,...,...,...,...,...,...
1000,1011,Neha,43.0,Mumbai,Marketing,14.0,64350.0,80.9,5.0,2026.0
1001,1026,Aman,20.0,Mumbai,Sales,3.0,89418.0,57.1,6.0,2021.0
1002,1051,Kabir,45.0,Jaipur,Finance,19.0,108014.0,93.9,2.0,2020.0
1003,1076,Anjali,36.0,Mumbai,IT,5.0,40408.0,47.2,2.0,2017.0
1004,1101,Riya,32.0,Kolkata,Sales,13.0,70541.0,49.1,6.0,2023.0

In [112]:
df['Experience_Years']=df['Experience_Years'].fillna(df['Experience_Years'].median())

In [113]:
df.isna().sum()

ID                   0
Name                 0
Age                  0
City                 0
Department           0
Experience_Years     0
Salary               0
Performance_Score    0
Projects             0
Joining_Year         0
dtype: int64

# df.dropna()

 missing values ko delete karte hain.

Jis row mein ek bhi missing value hai, poori row delete.

# df.dropna(subset=["Salary"])

Sirf Salary ki missing values wali rows delete karega.

# df.dropna(axis=1)

Ab rows nahi, columns delete karenge.

# df.ffill()

ffill = Forward Fill

Missing value ko upar wali previous value se fill karo.

# df.bfill()

bfill = Backward Fill

Missing value ko neeche wali next value se fill karo.

# interpolate()

Ye missing value ko aas-paas ki values ko dekhkar estimate karta hai.

interpolate() numeric data ke liye zyada useful hai, jaise:

In [114]:
#Duplicate KAHAN hain?

df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1000     True
1001     True
1002     True
1003     True
1004     True
Length: 1005, dtype: bool

In [115]:
# Duplicate KITNE hain?

df.duplicated().sum()

np.int64(5)

In [116]:
# poori row ko compare nahi karenge.
#Sirf Name column ko check karenge:


df.duplicated(subset=['Name'])

0       False
1       False
2       False
3       False
4        True
        ...
1000     True
1001     True
1002     True
1003     True
1004     True
Length: 1005, dtype: bool

In [117]:
# Duplicate group ki pehli value ko original rakho, baaki ko duplicate (True) bolo.

df.duplicated(keep='first')

0       False
1       False
2       False
3       False
4       False
        ...
1000     True
1001     True
1002     True
1003     True
1004     True
Length: 1005, dtype: bool

In [118]:
df.duplicated(keep='last')

0       False
1       False
2       False
3       False
4       False
        ...
1000    False
1001    False
1002    False
1003    False
1004    False
Length: 1005, dtype: bool

In [119]:
# Duplicate group ki saari values ko True karo.

df.duplicated(keep=False)

0       False
1       False
2       False
3       False
4       False
        ...
1000     True
1001     True
1002     True
1003     True
1004     True
Length: 1005, dtype: bool

In [120]:
#Agar tum saare duplicate records dekhna chahte ho:

df[df.duplicated(keep=False)]

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
10,1011,Neha,43.0,Mumbai,Marketing,14.0,64350.0,80.9,5.0,2026.0
25,1026,Aman,20.0,Mumbai,Sales,3.0,89418.0,57.1,6.0,2021.0
50,1051,Kabir,45.0,Jaipur,Finance,19.0,108014.0,93.9,2.0,2020.0
75,1076,Anjali,36.0,Mumbai,IT,5.0,40408.0,47.2,2.0,2017.0
100,1101,Riya,32.0,Kolkata,Sales,13.0,70541.0,49.1,6.0,2023.0
1000,1011,Neha,43.0,Mumbai,Marketing,14.0,64350.0,80.9,5.0,2026.0
1001,1026,Aman,20.0,Mumbai,Sales,3.0,89418.0,57.1,6.0,2021.0
1002,1051,Kabir,45.0,Jaipur,Finance,19.0,108014.0,93.9,2.0,2020.0
1003,1076,Anjali,36.0,Mumbai,IT,5.0,40408.0,47.2,2.0,2017.0
1004,1101,Riya,32.0,Kolkata,Sales,13.0,70541.0,49.1,6.0,2023.0

In [121]:
# Ye duplicate complete rows ko remove karega.

df=df.drop_duplicates()
df

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,1001,Arjun,20.0,Pune,Finance,5.0,49519.0,66.6,4.0,2015.0
1,1002,Neha,34.0,Bhopal,Marketing,0.0,47439.0,71.9,9.0,2020.0
2,1003,Simran,27.0,Indore,HR,19.0,101949.0,92.4,8.0,2016.0
3,1004,Rahul,30.0,Mumbai,Sales,15.0,39995.0,99.7,9.0,2020.0
4,1005,Arjun,33.0,Jaipur,Marketing,14.0,48559.0,75.0,4.0,2024.0
...,...,...,...,...,...,...,...,...,...,...
995,1996,Anjali,43.0,Pune,IT,16.0,87047.0,47.8,9.0,2016.0
996,1997,Anjali,34.0,Kolkata,Sales,5.0,98290.0,52.2,0.0,2017.0
997,1998,Simran,34.0,Pune,HR,1.0,72014.0,86.1,0.0,2018.0
998,1999,Riya,25.0,Lucknow,Sales,3.0,29078.0,65.5,5.0,2024.0
999,2000,Vikas,31.0,Lucknow,HR,10.0,103389.0,73.9,1.0,2020.0

In [122]:
df.duplicated().sum()

np.int64(0)

In [123]:
df=df.drop_duplicates(subset=['Name'])
df

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,1001,Arjun,20.0,Pune,Finance,5.0,49519.0,66.6,4.0,2015.0
1,1002,Neha,34.0,Bhopal,Marketing,0.0,47439.0,71.9,9.0,2020.0
2,1003,Simran,27.0,Indore,HR,19.0,101949.0,92.4,8.0,2016.0
3,1004,Rahul,30.0,Mumbai,Sales,15.0,39995.0,99.7,9.0,2020.0
5,1006,Anjali,31.0,Mumbai,Sales,16.0,114049.0,88.7,0.0,2022.0
6,1007,Kabir,23.0,Delhi,Sales,7.0,30021.0,59.6,8.0,2016.0
14,1015,Priya,36.0,Pune,Sales,5.0,47250.0,47.7,1.0,2024.0
16,1017,Riya,28.0,Bhopal,IT,20.0,107895.0,81.6,6.0,2020.0
21,1022,Aman,28.0,Delhi,Marketing,15.0,84546.0,83.8,5.0,2026.0
24,1025,Vikas,42.0,Indore,HR,20.0,54768.0,41.5,0.0,2017.0

In [124]:
df.duplicated(subset=['Name']).sum()

np.int64(0)

# unique(),= Unique values dikhao

 # nunique(), = Unique values dikhao

 # value_counts(), = Ye batata hai ki har value kitni baar aayi hai.

In [125]:
df['City'].unique()

array(['Pune', 'Bhopal', 'Indore', 'Mumbai', 'Delhi'], dtype=object)

In [126]:
df['City'].nunique()

5

In [127]:
df['City'].value_counts()

City
Pune      2
Bhopal    2
Indore    2
Mumbai    2
Delhi     2
Name: count, dtype: int64

In [128]:
# Ab count ke badle  decimal form milega.

df['City'].value_counts(normalize=True)

City
Pune      0.2
Bhopal    0.2
Indore    0.2
Mumbai    0.2
Delhi     0.2
Name: proportion, dtype: float64

In [129]:
# Ye percentage deta hai.

df['City'].value_counts(normalize=True)*100

City
Pune      20.0
Bhopal    20.0
Indore    20.0
Mumbai    20.0
Delhi     20.0
Name: proportion, dtype: float64

In [130]:
# NaN ko bhi count karta hai

df['City'].value_counts(dropna=False)

City
Pune      2
Bhopal    2
Indore    2
Mumbai    2
Delhi     2
Name: count, dtype: int64

In [131]:
df['City'].unique()
df['City'].nunique()
df['City'].value_counts()
df['City'].value_counts(normalize=True)*100

City
Pune      20.0
Bhopal    20.0
Indore    20.0
Mumbai    20.0
Delhi     20.0
Name: proportion, dtype: float64

In [132]:
## Data type

In [133]:
df.dtypes

ID                     int64
Name                  object
Age                  float64
City                  object
Department            object
Experience_Years     float64
Salary               float64
Performance_Score    float64
Projects             float64
Joining_Year         float64
dtype: object

In [134]:
df['Age'].isna().sum()

np.int64(0)

In [135]:
# Age column ko integer (int64) mein convert karta hai.
# int64 missing NaN ko handle nahi karta.

df['Age']=df['Age'].astype('int64')

/tmp/ipykernel_2303/4181193963.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age']=df['Age'].astype('int64')

In [136]:
df['Age'].dtypes

dtype('int64')

In [137]:
#coerce ka simple meaning:
#Jo value number mein convert nahi ho sakti, usko NaN bana do.
# ye text or string data ko numeric data me convert krta hai


df['City']=pd.to_numeric(df['City'],errors='coerce')

/tmp/ipykernel_2303/4168856427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City']=pd.to_numeric(df['City'],errors='coerce')

In [138]:
df['City'].dtypes

dtype('float64')

In [ ]:
#Iska kaam hai date ko proper Pandas date/time format mein convert karna

df['Date']=pd.to_datetime(df['Date'],errors='coerce')

# df["Name"].str.lower()

➡️ Sabhi text ko small letters mein convert karta hai.

# df["Name"].str.upper()

➡️ Sabhi text ko CAPITAL letters mein convert karta hai.

# df["Name"].str.title()

➡️ Har word ka first letter capital karta hai.

# df["Name"].str.strip()

➡️ String ke starting aur ending ke extra spaces remove karta hai.

# df["Name"].str.len()

➡️ Har string mein kitne characters hain, ye batata hai.

# df["Name"].str.contains("a", case=False, na=False)

Ye check karta hai ki Name ke andar a hai ya nahi.

# df["Name"].str.startswith("A")

➡️ Check karta hai ki string A se start ho rahi hai ya nahi.

# df["Name"].str.endswith("a")

➡️ Check karta hai ki string a par end ho rahi hai ya nahi.

# .str.split("@").str[1]

Ye Email se domain nikalne ke liye bahut useful hai.

# df["Name"].str.replace("Aman", "Amit", regex=False)

➡️ Name mein "Aman" ko "Amit" se replace karta hai.

# df["Text"].str.extract(r"(\d+)", expand=False)

Iska use text ke andar se number nikalne ke liye hota hai.

In [141]:
df['Name'].str.lower().head()

0     arjun
1      neha
2    simran
3     rahul
5    anjali
Name: Name, dtype: object

In [142]:
df['Name'].str.upper().head()

0     ARJUN
1      NEHA
2    SIMRAN
3     RAHUL
5    ANJALI
Name: Name, dtype: object

In [143]:
df['Name'].str.title().head()

0     Arjun
1      Neha
2    Simran
3     Rahul
5    Anjali
Name: Name, dtype: object

In [144]:
df['Name'].str.startswith('A').head()

0     True
1    False
2    False
3    False
5     True
Name: Name, dtype: bool

In [146]:
df['Name'].str.endswith('a').head()

0    False
1     True
2    False
3    False
5    False
Name: Name, dtype: bool

In [145]:
df['Name'].str.len().head()

0    5
1    4
2    6
3    5
5    6
Name: Name, dtype: int64

In [147]:
df['Name'].str.replace('Arjun','Neha',regex=False).head()

0      Neha
1      Neha
2    Simran
3     Rahul
5    Anjali
Name: Name, dtype: object

In [148]:
cities = ["Indore", "Delhi", "Mumbai", "Pune"]

df["City"] = [cities[i % 4] for i in range(len(df))]
df.head()

/tmp/ipykernel_2303/4004234054.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = [cities[i % 4] for i in range(len(df))]

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year
0,1001,Arjun,20,Indore,Finance,5.0,49519.0,66.6,4.0,2015.0
1,1002,Neha,34,Delhi,Marketing,0.0,47439.0,71.9,9.0,2020.0
2,1003,Simran,27,Mumbai,HR,19.0,101949.0,92.4,8.0,2016.0
3,1004,Rahul,30,Pune,Sales,15.0,39995.0,99.7,9.0,2020.0
5,1006,Anjali,31,Indore,Sales,16.0,114049.0,88.7,0.0,2022.0

In [149]:
df['City'].head()

0    Indore
1     Delhi
2    Mumbai
3      Pune
5    Indore
Name: City, dtype: object

In [150]:
# replace()

# Kaam: kisi value ko doosri value se change karna.

df['City']=df['City'].replace({
    'Indore':'Delhi'

})
df['City'].head()

/tmp/ipykernel_2303/2159194756.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City']=df['City'].replace({

0     Delhi
1     Delhi
2    Mumbai
3      Pune
5     Delhi
Name: City, dtype: object

In [151]:
# One-Hot Encoding kya hai?
# One-Hot Encoding categorical/text data ko 0 aur 1 ke form me convert karta hai, taaki Machine Learning model us data ko samajh sake.


pd.get_dummies(df,columns=['City'],dtype=int).head()

,ID,Name,Age,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year,City_Delhi,City_Mumbai,City_Pune
0,1001,Arjun,20,Finance,5.0,49519.0,66.6,4.0,2015.0,1,0,0
1,1002,Neha,34,Marketing,0.0,47439.0,71.9,9.0,2020.0,1,0,0
2,1003,Simran,27,HR,19.0,101949.0,92.4,8.0,2016.0,0,1,0
3,1004,Rahul,30,Sales,15.0,39995.0,99.7,9.0,2020.0,0,0,1
5,1006,Anjali,31,Sales,16.0,114049.0,88.7,0.0,2022.0,1,0,0

In [152]:
 # lambda function

square=lambda x:x*x
square(3)

9

In [159]:
df['Age']

0     45.0
1     59.0
2     52.0
3     55.0
5     56.0
6      NaN
14     NaN
16     NaN
21     NaN
24     NaN
Name: Age, dtype: float64

In [158]:
df['Age2']=df['Age'].apply(lambda x:x+5)
df.head(5)

/tmp/ipykernel_2303/3254979162.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age2']=df['Age'].apply(lambda x:x+5)

,ID,Name,Age,City,Department,Experience_Years,Salary,Performance_Score,Projects,Joining_Year,Age2
0,1001,Arjun,45.0,Delhi,Finance,5.0,49519.0,66.6,4.0,2015.0,50.0
1,1002,Neha,59.0,Delhi,Marketing,0.0,47439.0,71.9,9.0,2020.0,64.0
2,1003,Simran,52.0,Mumbai,HR,19.0,101949.0,92.4,8.0,2016.0,57.0
3,1004,Rahul,55.0,Pune,Sales,15.0,39995.0,99.7,9.0,2020.0,60.0
5,1006,Anjali,56.0,Delhi,Sales,16.0,114049.0,88.7,0.0,2022.0,61.0

In [163]:
print(df.groupby("City")["Salary"].mean())

City
Delhi     63390.333333
Mumbai    74599.500000
Pune      73945.000000
Name: Salary, dtype: float64