<a href="https://colab.research.google.com/github/amitsingh6261/my_all_python_Program/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# deffination of pandas
# pandas is an open source pyhton library used for data manipulation, data analylis, and handling structured data
#in the form of rows and columns.

In [39]:
import pandas as pd

df = {
    "Name":("Aman","Riya","Kabir","Neha","Aman","Amit"),
    "Age":(21,22,20,23,21,21),
    "City":("Delhi","Mumbai","Delhi","Pune","Delhi","Indore"),
    "Marks":(85,92,76,88,85,95),
    "Salary":(45000,52000,39000,61000,45000,90000)
}

In [40]:
df=pd.DataFrame(df)
df

    Name  Age    City  Marks  Salary
0   Aman   21   Delhi     85   45000
1   Riya   22  Mumbai     92   52000
2  Kabir   20   Delhi     76   39000
3   Neha   23    Pune     88   61000
4   Aman   21   Delhi     85   45000
5   Amit   21  Indore     95   90000

In [41]:
#show starting value
df.head(2)

   Name  Age    City  Marks  Salary
0  Aman   21   Delhi     85   45000
1  Riya   22  Mumbai     92   52000

In [42]:
#show last values
df.tail(3)

   Name  Age    City  Marks  Salary
3  Neha   23    Pune     88   61000
4  Aman   21   Delhi     85   45000
5  Amit   21  Indore     95   90000

In [43]:
#show total row and columns
df.shape

(6, 5)

In [44]:
# shoe all columns
df.columns

Index(['Name', 'Age', 'City', 'Marks', 'Salary'], dtype='object')

In [45]:
# show index
df.index

RangeIndex(start=0, stop=6, step=1)

In [46]:
# show data type
df.dtypes

Name      object
Age        int64
City      object
Marks      int64
Salary     int64
dtype: object

In [47]:
#df.info() → DataFrame ki basic information deta hai.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
 3   Marks   6 non-null      int64
 4   Salary  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

In [48]:
#df.describe() → Sirf numbers ka summary deta hai.
df.describe()

             Age      Marks        Salary
count   6.000000   6.000000      6.000000
mean   21.333333  86.833333  55333.333333
std     1.032796   6.615638  18575.970141
min    20.000000  76.000000  39000.000000
25%    21.000000  85.000000  45000.000000
50%    21.000000  86.500000  48500.000000
75%    21.750000  91.000000  58750.000000
max    23.000000  95.000000  90000.000000

In [49]:
#df.describe(include="all") → Saare columns ka summary deta hai.
df.describe(include="all")

        Name        Age   City      Marks        Salary
count      6   6.000000      6   6.000000      6.000000
unique     5        NaN      4        NaN           NaN
top     Aman        NaN  Delhi        NaN           NaN
freq       2        NaN      3        NaN           NaN
mean     NaN  21.333333    NaN  86.833333  55333.333333
std      NaN   1.032796    NaN   6.615638  18575.970141
min      NaN  20.000000    NaN  76.000000  39000.000000
25%      NaN  21.000000    NaN  85.000000  45000.000000
50%      NaN  21.000000    NaN  86.500000  48500.000000
75%      NaN  21.750000    NaN  91.000000  58750.000000
max      NaN  23.000000    NaN  95.000000  90000.000000

In [50]:
# select from DataFrame
df[['Name','Marks']]

    Name  Marks
0   Aman     85
1   Riya     92
2  Kabir     76
3   Neha     88
4   Aman     85
5   Amit     95

In [51]:
# select from  Series
df['Name']

0     Aman
1     Riya
2    Kabir
3     Neha
4     Aman
5     Amit
Name: Name, dtype: object

In [52]:
df.Name

0     Aman
1     Riya
2    Kabir
3     Neha
4     Aman
5     Amit
Name: Name, dtype: object

In [53]:
df.iloc[2,0]

'Kabir'

#  loc vs iloc

# loc = index/label dekhta hai (kis index per value hai)
# iloc = position dekhta hai(kis possion per value hai)
#loc → Label/Index aur column ke naam par kaam karta hai.
#Example: df.loc[1, "Name"]
#iloc → Integer position (0, 1, 2...) par kaam karta hai.
#Example: df.iloc[1, 0]

In [54]:
df.iloc[2,0]

'Kabir'

In [55]:
df.loc[2,'Name']

'Kabir'

# Filtering

# data filtering is the prosecc of selecting only the required data from a dataser based on the given condtion

In [56]:
dt=pd.DataFrame({
     "Name":['Amit','Rohit','Nitin','Ram','Shyam','Naman'],
     "Age":[21,43,54,23,54,65],
     "City":['Indore','pune','delhi','agra','noida','devash'],
     "Marks":[99,78,98,96,85,93]
 })

In [57]:
dt

    Name  Age    City  Marks
0   Amit   21  Indore     99
1  Rohit   43    pune     78
2  Nitin   54   delhi     98
3    Ram   23    agra     96
4  Shyam   54   noida     85
5  Naman   65  devash     93

In [58]:
dt['Marks']>95

0     True
1    False
2     True
3     True
4    False
5    False
Name: Marks, dtype: bool

In [59]:
dt[dt['Marks']>95]

    Name  Age    City  Marks
0   Amit   21  Indore     99
2  Nitin   54   delhi     98
3    Ram   23    agra     96

3. Filtering ka Basic Formula

Isko yaad kar lo:

df[df["column"] condition]

AND → &

OR  → |

In [60]:
dt[dt['Age']>45]

    Name  Age    City  Marks
2  Nitin   54   delhi     98
4  Shyam   54   noida     85
5  Naman   65  devash     93

In [61]:
#99 ko chhod kar
dt[dt['Marks']!=99]

    Name  Age    City  Marks
1  Rohit   43    pune     78
2  Nitin   54   delhi     98
3    Ram   23    agra     96
4  Shyam   54   noida     85
5  Naman   65  devash     93

In [62]:
dt[dt['City']=='pune']

    Name  Age  City  Marks
1  Rohit   43  pune     78

In [63]:
dt[(dt['Age']>45)&(dt['Marks']>90)]

    Name  Age    City  Marks
2  Nitin   54   delhi     98
5  Naman   65  devash     93

In [64]:
dt[(dt['City']=='pune')|(dt['Marks']>90)]

    Name  Age    City  Marks
0   Amit   21  Indore     99
1  Rohit   43    pune     78
2  Nitin   54   delhi     98
3    Ram   23    agra     96
5  Naman   65  devash     93

In [65]:
df[df["Marks"] > 80]["Name"]

0    Aman
1    Riya
3    Neha
4    Aman
5    Amit
Name: Name, dtype: object