<a href="https://colab.research.google.com/github/amitsingh6261/my_all_python_Program/blob/main/pandas_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df_8=pd.read_csv("/content/all_alpha_08.csv")
df_18=pd.read_csv("/content/all_alpha_18.csv")

In [ ]:
df_8

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Stnd,Underhood ID,Veh Class,Air Pollution Score,FE Calc Appr,City MPG,Hwy MPG,Cmb MPG,Unadj Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT03.7PKR,SUV,7,Drv,15,20,17,22.0527,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT03.7PKR,SUV,6,Drv,15,20,17,22.0527,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT02.3DKR,SUV,7,Drv,17,22,19,24.1745,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT02.3DKR,SUV,6,Drv,17,22,19,24.1745,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXV03.5HKR,midsize car,7,Drv,16,24,19,24.5629,5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,CA,U2,8VVXB03.2U2N,SUV,7,Drv,14,20,16,20.7134,4,no
2400,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,CA,U2,8VVXB04.4U2N,SUV,7,Drv,13,19,15,19.4789,3,no
2401,VOLVO XC 90,3.2,(6 cyl),Auto-S6,2WD,Gasoline,FA,B5,8VVXB03.2U2N,SUV,6,Drv,14,20,16,20.9644,4,no
2402,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,FA,B5,8VVXB03.2U2N,SUV,6,Drv,14,20,16,20.7134,4,no
2403,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,FA,B5,8VVXB04.4U2N,SUV,6,Drv,13,19,15,19.4789,3,no

In [ ]:
df_18

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Stnd,Stnd Description,Underhood ID,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay,Comb CO2
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,T3B125,Federal Tier 3 Bin 125,JHNXT03.5GV3,small SUV,3,20,28,23,5,No,386
1,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,CA,U2,California LEV-II ULEV,JHNXT03.5GV3,small SUV,3,20,28,23,5,No,386
2,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,FA,T3B125,Federal Tier 3 Bin 125,JHNXT03.5GV3,small SUV,3,19,27,22,4,No,402
3,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,CA,U2,California LEV-II ULEV,JHNXT03.5GV3,small SUV,3,19,27,22,4,No,402
4,ACURA TLX,2.4,4.0,AMS-8,2WD,Gasoline,CA,L3ULEV125,California LEV-III ULEV125,JHNXV02.4WH3,small car,3,23,33,27,6,No,330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1606,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,T3B70,Federal Tier 3 Bin 70,JVVXJ02.0A70,standard SUV,5,22,28,24,5,No,365
1607,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,CA,L3ULEV70,California LEV-III ULEV70,JVVXJ02.0B70,standard SUV,5,20,27,23,5,No,394
1608,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,FA,T3B70,Federal Tier 3 Bin 70,JVVXJ02.0B70,standard SUV,5,20,27,23,5,No,394
1609,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,CA,L3SULEV30,California LEV-III SULEV30,JVVXJ02.0P30,standard SUV,7,26/63,30/61,27/62,10,Elite,187
1610,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,FA,T3B30,Federal Tier 3 Bin 30,JVVXJ02.0P30,standard SUV,7,26/63,30/61,27/62,10,Elite,187

In [ ]:
df_8.shape , df_18.shape

((2404, 18), (1611, 18))

In [ ]:
df_8.duplicated().sum(), df_18.duplicated().sum()

(np.int64(25), np.int64(0))

In [ ]:
df_8.isnull().sum(), df_18.isnull().sum()

(Model                     0
 Displ                     0
 Cyl                     199
 Trans                   199
 Drive                    93
 Fuel                      0
 Sales Area                0
 Stnd                      0
 Underhood ID              0
 Veh Class                 0
 Air Pollution Score       0
 FE Calc Appr            199
 City MPG                199
 Hwy MPG                 199
 Cmb MPG                 199
 Unadj Cmb MPG           199
 Greenhouse Gas Score    199
 SmartWay                  0
 dtype: int64,
 Model                   0
 Displ                   2
 Cyl                     2
 Trans                   0
 Drive                   0
 Fuel                    0
 Cert Region             0
 Stnd                    0
 Stnd Description        0
 Underhood ID            0
 Veh Class               0
 Air Pollution Score     0
 City MPG                0
 Hwy MPG                 0
 Cmb MPG                 0
 Greenhouse Gas Score    0
 SmartWay                0
 Comb CO2                0
 dtype: int64)

In [ ]:
df_8.nunique(),df_18.nunique()

(Model                   436
 Displ                    47
 Cyl                       8
 Trans                    14
 Drive                     2
 Fuel                      5
 Sales Area                3
 Stnd                     12
 Underhood ID            343
 Veh Class                 9
 Air Pollution Score      13
 FE Calc Appr              2
 City MPG                 39
 Hwy MPG                  43
 Cmb MPG                  38
 Unadj Cmb MPG           721
 Greenhouse Gas Score     20
 SmartWay                  2
 dtype: int64,
 Model                   367
 Displ                    36
 Cyl                       7
 Trans                    26
 Drive                     2
 Fuel                      5
 Cert Region               2
 Stnd                     19
 Stnd Description         19
 Underhood ID            230
 Veh Class                 9
 Air Pollution Score       6
 City MPG                 58
 Hwy MPG                  62
 Cmb MPG                  57
 Greenhouse Gas Score     10
 SmartWay                  3
 Comb CO2                299
 dtype: int64)

In [ ]:
df_18.nunique()

Model                   367
Displ                    36
Cyl                       7
Trans                    26
Drive                     2
Fuel                      5
Cert Region               2
Stnd                     19
Stnd Description         19
Underhood ID            230
Veh Class                 9
Air Pollution Score       6
City MPG                 58
Hwy MPG                  62
Cmb MPG                  57
Greenhouse Gas Score     10
SmartWay                  3
Comb CO2                299
dtype: int64

In [ ]:
df_8.columns

Index(['Model', 'Displ', 'Cyl', 'Trans', 'Drive', 'Fuel', 'Sales Area', 'Stnd',
       'Underhood ID', 'Veh Class', 'Air Pollution Score', 'FE Calc Appr',
       'City MPG', 'Hwy MPG', 'Cmb MPG', 'Unadj Cmb MPG',
       'Greenhouse Gas Score', 'SmartWay'],
      dtype='object')

In [ ]:
df_18.columns

Index(['Model', 'Displ', 'Cyl', 'Trans', 'Drive', 'Fuel', 'Cert Region',
       'Stnd', 'Stnd Description', 'Underhood ID', 'Veh Class',
       'Air Pollution Score', 'City MPG', 'Hwy MPG', 'Cmb MPG',
       'Greenhouse Gas Score', 'SmartWay', 'Comb CO2'],
      dtype='object')

In [ ]:
df_8.drop(columns=['Stnd', 'Underhood ID','FE Calc Appr','Unadj Cmb MPG'],inplace=True)
df_18.drop(columns=['Stnd','Stnd Description', 'Underhood ID', 'Comb CO2'],inplace=True)

In [ ]:
df_8.rename(columns={'sales_area':'cert_region'},inplace=True)

In [ ]:
df_8.rename(columns=lambda x: x.strip().lower().replace(" ","_"),inplace=True)
df_18.rename(columns=lambda x: x.strip().lower().replace(" ","_"),inplace=True)

In [ ]:
df_18.head(1)

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,small SUV,3,20,28,23,5,No

In [ ]:
df_8.head(1)

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no

In [ ]:
df_8.columns == df_18.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [ ]:
(df_8.columns == df_18.columns).all()

np.True_

In [ ]:
df_8.columns

Index(['model', 'displ', 'cyl', 'trans', 'drive', 'fuel', 'sales_area',
       'veh_class', 'air_pollution_score', 'city_mpg', 'hwy_mpg', 'cmb_mpg',
       'greenhouse_gas_score', 'smartway'],
      dtype='object')

In [ ]:
df_18.columns

Index(['model', 'displ', 'cyl', 'trans', 'drive', 'fuel', 'cert_region',
       'veh_class', 'air_pollution_score', 'city_mpg', 'hwy_mpg', 'cmb_mpg',
       'greenhouse_gas_score', 'smartway'],
      dtype='object')

In [ ]:
#jo data per operation kiye hai us data ko download karne ke liye matlab (filter data download krne ke liye)
df_8.to_csv('data_8_V1.csv' , index=False)
df_18.to_csv('data_18_V1.csv' , index=False)

In [ ]:
# show filter data
df_8=pd.read_csv('/content/data_8_V1.csv')
df_18=pd.read_csv('/content/data_18_V1.csv')

In [ ]:
df_8

,Unnamed: 0,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
1,1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,15,20,17,4,no
2,2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
3,3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,17,22,19,5,no
4,4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399,2399,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,14,20,16,4,no
2400,2400,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,13,19,15,3,no
2401,2401,VOLVO XC 90,3.2,(6 cyl),Auto-S6,2WD,Gasoline,FA,SUV,6,14,20,16,4,no
2402,2402,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,FA,SUV,6,14,20,16,4,no
2403,2403,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,FA,SUV,6,13,19,15,3,no

In [ ]:
df_8.query('cert_region == "CA"').head()

,Unnamed: 0,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
2,2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
4,4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
6,6,ACURA TL,3.2,(6 cyl),Auto-S5,2WD,Gasoline,CA,midsize car,7,18,26,21,6,yes
7,7,ACURA TL,3.5,(6 cyl),Auto-S5,2WD,Gasoline,CA,midsize car,7,17,26,20,6,yes

In [ ]:
df_8.drop(['cert_region'],axis =1, inplace=True)
df_18.drop(['cert_region'],axis =1, inplace=True)

In [ ]:
df_8.isnull().sum()

Unnamed: 0                0
model                     0
displ                     0
cyl                     199
trans                   199
drive                    93
fuel                      0
veh_class                 0
air_pollution_score       0
city_mpg                199
hwy_mpg                 199
cmb_mpg                 199
greenhouse_gas_score    199
smartway                  0
dtype: int64

In [ ]:
df_8.dropna(inplace=True)

In [ ]:
df_8.isnull().sum()

Unnamed: 0              0
model                   0
displ                   0
cyl                     0
trans                   0
drive                   0
fuel                    0
veh_class               0
air_pollution_score     0
city_mpg                0
hwy_mpg                 0
cmb_mpg                 0
greenhouse_gas_score    0
smartway                0
dtype: int64

In [ ]:
df_18.isnull().sum()

Unnamed: 0              0
model                   0
displ                   2
cyl                     2
trans                   0
drive                   0
fuel                    0
veh_class               0
air_pollution_score     0
city_mpg                0
hwy_mpg                 0
cmb_mpg                 0
greenhouse_gas_score    0
smartway                0
dtype: int64

In [ ]:
df_18.dropna(inplace=True)

In [ ]:
df_18.isnull().sum()

Unnamed: 0              0
model                   0
displ                   0
cyl                     0
trans                   0
drive                   0
fuel                    0
veh_class               0
air_pollution_score     0
city_mpg                0
hwy_mpg                 0
cmb_mpg                 0
greenhouse_gas_score    0
smartway                0
dtype: int64

In [ ]:
df_8.isnull().sum()==df_18.isnull().sum()

Unnamed: 0              True
model                   True
displ                   True
cyl                     True
trans                   True
drive                   True
fuel                    True
veh_class               True
air_pollution_score     True
city_mpg                True
hwy_mpg                 True
cmb_mpg                 True
greenhouse_gas_score    True
smartway                True
dtype: bool

In [ ]:
df_8.isnull().sum().any()==df_18.isnull().sum().any()

In [ ]:
df_8.duplicated().sum(), df_18.duplicated().sum()

(np.int64(0), np.int64(0))

In [ ]:
df_8.drop_duplicates(inplace=True)
df_18.drop_duplicates(inplace=True)

In [ ]:
df_8.duplicated().sum(), df_18.duplicated().sum()

(np.int64(0), np.int64(0))

In [ ]:
df_8.to_csv('data_8_V2.csv' , index=False)
df_18.to_csv('data_18_V2.csv' , index=False)

In [ ]:
df_8=pd.read_csv('/content/data_8_V2.csv')
df_18=pd.read_csv('/content/data_18_V2.csv')

In [ ]:
df_8

,Unnamed: 0,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,SUV,7,15,20,17,4,no
1,1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,SUV,6,15,20,17,4,no
2,2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,SUV,7,17,22,19,5,no
3,3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,SUV,6,17,22,19,5,no
4,4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,midsize car,7,16,24,19,5,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,2399,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,SUV,7,14,20,16,4,no
2201,2400,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,SUV,7,13,19,15,3,no
2202,2401,VOLVO XC 90,3.2,(6 cyl),Auto-S6,2WD,Gasoline,SUV,6,14,20,16,4,no
2203,2402,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,SUV,6,14,20,16,4,no
2204,2403,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,SUV,6,13,19,15,3,no

In [ ]:
df_18

,Unnamed: 0,model,displ,cyl,trans,drive,fuel,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,small SUV,3,20,28,23,5,No
1,1,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,small SUV,3,20,28,23,5,No
2,2,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,small SUV,3,19,27,22,4,No
3,3,ACURA RDX,3.5,6.0,SemiAuto-6,4WD,Gasoline,small SUV,3,19,27,22,4,No
4,4,ACURA TLX,2.4,4.0,AMS-8,2WD,Gasoline,small car,3,23,33,27,6,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1604,1606,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,standard SUV,5,22,28,24,5,No
1605,1607,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,standard SUV,5,20,27,23,5,No
1606,1608,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline,standard SUV,5,20,27,23,5,No
1607,1609,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,standard SUV,7,26/63,30/61,27/62,10,Elite
1608,1610,VOLVO XC 90,2.0,4.0,SemiAuto-8,4WD,Gasoline/Electricity,standard SUV,7,26/63,30/61,27/62,10,Elite